# Generated by Django 4.2.19 on 2025-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_generate_bulk_coupons',
            field=models.BooleanField(default=False),
        ),
    ]
