# Generated by Django 4.2.19 on 2025-03-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courses',
        ),
        migrations.AddField(
            model_name='order',
            name='stored_ids',
            field=models.TextField(default='[]'),
        ),
    ]
