# Generated by Django 4.2.19 on 2025-03-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='merchant',
        ),
    ]
