# Generated by Django 4.2.19 on 2025-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
