# Generated by Django 5.1.6 on 2025-02-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0002_course_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mac_address',
            new_name='android_id',
        ),
    ]
