# Generated by Django 4.2.19 on 2025-03-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0002_remove_order_courses_order_stored_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer_phone',
            new_name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_email',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
