# Generated by Django 4.2.19 on 2025-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0002_customuser_can_generate_bulk_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
