# Generated by Django 4.2.19 on 2025-03-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_back', '0002_rename_user_device_merchant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
